In [1]:
import numpy as np
import pandas as pd
import matplotlib


In [5]:
a = np.array([1,2,3,4,5,8,], float)

In [10]:
print(a)

[1. 2. 3. 4. 5. 8.]


In [7]:
b = np.array([1.0,4.0, 3.0 ,6.0, 8.0, 9.0], int)

In [9]:
b

array([1, 4, 3, 6, 8, 9])

In [11]:
print(b)

[1 4 3 6 8 9]


In [12]:
a[:2]

array([1., 2.])

In [13]:
a[0]

1.0

In [14]:
b[5]

9

In [21]:
d = np.array([[1,4,5,2,3,9],[9,6,4,5,2,3]], float)

In [22]:
print(d)

[[1. 4. 5. 2. 3. 9.]
 [9. 6. 4. 5. 2. 3.]]


In [23]:
d

array([[1., 4., 5., 2., 3., 9.],
       [9., 6., 4., 5., 2., 3.]])

In [24]:
d.shape


(2, 6)

In [67]:
d[0,0]
d[0,1]
d[0,2]
d[0,3]
d[0,4]
d[0,5]
d[1,0]
d[1,2]
d[1,3]
d[1,4]
d[1,5]


3.0

In [31]:
d[0,1]

4.0

In [32]:
d[1,5]

3.0

In [33]:
d[0,5]

9.0

In [34]:
d.dtype

dtype('float64')

In [37]:
d.shape

(2, 6)

In [36]:
d.shape

(2, 6)

In [38]:
len(d)

2

In [39]:
9.0 in d

True

In [40]:
10.0 in d

False

In [54]:
e = np.array(range(10),float)

e = e.reshape((5,2))

In [55]:
e

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [56]:
e.shape

(5, 2)

In [60]:
#Lists can also be created from arrays:

f = e.tolist()

In [61]:
list(f)

[[0.0, 1.0], [2.0, 3.0], [4.0, 5.0], [6.0, 7.0], [8.0, 9.0]]

In [63]:
f 

[[0.0, 1.0], [2.0, 3.0], [4.0, 5.0], [6.0, 7.0], [8.0, 9.0]]

In [64]:
#One can convert the raw data in an array to a binary string

g = e.tostring()

In [65]:
g

b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@\x00\x00\x00\x00\x00\x00 @\x00\x00\x00\x00\x00\x00"@'

In [66]:
np.fromstring(g)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [69]:
#Transposed versions of arrays 
i = np.array(range(100),float).reshape((25,4))

In [70]:
i

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.],
       [24., 25., 26., 27.],
       [28., 29., 30., 31.],
       [32., 33., 34., 35.],
       [36., 37., 38., 39.],
       [40., 41., 42., 43.],
       [44., 45., 46., 47.],
       [48., 49., 50., 51.],
       [52., 53., 54., 55.],
       [56., 57., 58., 59.],
       [60., 61., 62., 63.],
       [64., 65., 66., 67.],
       [68., 69., 70., 71.],
       [72., 73., 74., 75.],
       [76., 77., 78., 79.],
       [80., 81., 82., 83.],
       [84., 85., 86., 87.],
       [88., 89., 90., 91.],
       [92., 93., 94., 95.],
       [96., 97., 98., 99.]])

In [72]:
#transpose i

i.transpose()

array([[ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44., 48.,
        52., 56., 60., 64., 68., 72., 76., 80., 84., 88., 92., 96.],
       [ 1.,  5.,  9., 13., 17., 21., 25., 29., 33., 37., 41., 45., 49.,
        53., 57., 61., 65., 69., 73., 77., 81., 85., 89., 93., 97.],
       [ 2.,  6., 10., 14., 18., 22., 26., 30., 34., 38., 42., 46., 50.,
        54., 58., 62., 66., 70., 74., 78., 82., 86., 90., 94., 98.],
       [ 3.,  7., 11., 15., 19., 23., 27., 31., 35., 39., 43., 47., 51.,
        55., 59., 63., 67., 71., 75., 79., 83., 87., 91., 95., 99.]])

In [74]:
i.flatten()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [79]:
#concatenating two or more arrays


np.concatenate((a,b))




array([1., 2., 3., 4., 5., 8., 1., 4., 3., 6., 8., 9.])

In [87]:
#ARRAY mathematics
a+b

array([ 2.,  6.,  6., 10., 13., 17.])

In [81]:
a

array([1., 2., 3., 4., 5., 8.])

In [82]:
b

array([1, 4, 3, 6, 8, 9])

In [86]:

b/a

array([1.   , 2.   , 1.   , 1.5  , 1.6  , 1.125])

In [84]:
b*a


array([ 1.,  8.,  9., 24., 40., 72.])

In [85]:
b**a

array([1.0000000e+00, 1.6000000e+01, 2.7000000e+01, 1.2960000e+03,
       3.2768000e+04, 4.3046721e+07])

In [90]:
#Array iteration

a

array([1., 2., 3., 4., 5., 8.])

In [97]:
for x in a:
    print(x)

1.0
2.0
3.0
4.0
5.0
8.0


In [98]:
a.sum()

23.0

In [99]:
a.prod()

960.0

In [104]:
b.sum()

31

In [107]:
b.prod()

5184